os: linux
language: python
matrix:
  include:
    - env: TEST=flake8
      python: '3.6'
      install:
      - pip install flake8
      script:
      - flake8
      - flake8 --extend-ignore=F821 SConstruct */SConscript
    - env: TEST=shellcheck
      services:
        - docker
      script: |
        set -e
        shopt -s globstar nullglob
        CHECK=( **/*.sh )
        [[ ${#CHECK[@]} -eq 0 ]] && exit
        docker run -v $(pwd):$(pwd) -w $(pwd) \
          koalaman/shellcheck-alpine:v0.4.6 -x "${CHECK[@]}"
notifications:
  email: false
